FROM node:7.8-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ui/package.json /usr/src/app/
RUN yarn install

COPY ui /usr/src/app
RUN yarn run build && \
	tar -C build/ -zcvf build.tar.gz .

CMD ["cat", "/usr/src/app/build.tar.gz"]