FROM node:7.9-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN yarn install

COPY . /usr/src/app
RUN yarn run build && \
	tar -C build/ -zcvf build.tar.gz .

CMD ["cat", "/usr/src/app/build.tar.gz"]